// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOV0E0Yj7yVUWbXSgi15jmrPfhDJCxxro',
    appId: '1:1085478280853:web:0c4a0935e5740a6269c59c',
    messagingSenderId: '1085478280853',
    projectId: 'annadata-a28b9',
    authDomain: 'annadata-a28b9.firebaseapp.com',
    storageBucket: 'annadata-a28b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVr7z_JZoqWunNQQXw4BVVYCFhUrJgmg',
    appId: '1:1085478280853:android:4e69e7757b39707f69c59c',
    messagingSenderId: '1085478280853',
    projectId: 'annadata-a28b9',
    storageBucket: 'annadata-a28b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7AUHvc0sZB7j-tUgGNg8fUQbNiCuvs8',
    appId: '1:1085478280853:ios:6ddcceb6a4ce38e269c59c',
    messagingSenderId: '1085478280853',
    projectId: 'annadata-a28b9',
    storageBucket: 'annadata-a28b9.firebasestorage.app',
    iosClientId: '1085478280853-597ga6cbsfvtgq2jlq0hllbj49mtcn08.apps.googleusercontent.com',
    iosBundleId: 'com.example.annadatamart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7AUHvc0sZB7j-tUgGNg8fUQbNiCuvs8',
    appId: '1:1085478280853:ios:6ddcceb6a4ce38e269c59c',
    messagingSenderId: '1085478280853',
    projectId: 'annadata-a28b9',
    storageBucket: 'annadata-a28b9.firebasestorage.app',
    iosClientId: '1085478280853-597ga6cbsfvtgq2jlq0hllbj49mtcn08.apps.googleusercontent.com',
    iosBundleId: 'com.example.annadatamart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOV0E0Yj7yVUWbXSgi15jmrPfhDJCxxro',
    appId: '1:1085478280853:web:576589f896c8942969c59c',
    messagingSenderId: '1085478280853',
    projectId: 'annadata-a28b9',
    authDomain: 'annadata-a28b9.firebaseapp.com',
    storageBucket: 'annadata-a28b9.firebasestorage.app',
  );
}